# Data Validation Tutorial
Welcome to the data validation tutorial using tensorflow data validation! In this tutorial we will be using tensorflow data validation (or tfdv) to write data tests. The tutorial is divided into the following segments:

1. TFDV Exploration: we will start by exploring the fundamentals of tfdv.
2. Data validation: next we will write some *tests* for our data.

In [2]:
# put your import statements here
import tensorflow_data_validation as tfdv
import pandas as pd
from sklearn.model_selection import train_test_split

## Part 1: TFDV Exploration
In this section we will explore the basics of tfdv. Follow the instructions below.

### 1.1 Load the data
Use `pandas` to load the csv file as a dataframe.

+ *Hint*: did you check the [10 minutes with pandas guide]? Did you read the *Getting data in/out* section?
+ *Hint*: did you import pandas as `pd`?

[10 minutes with pandas guide]: https://pandas.pydata.org/docs/user_guide/10min.html

In [3]:
# your code here
df = pd.read_csv('data/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [5]:
df.shape

(569, 33)

### 1.2 Create train-test split
Use sklearn to create a 75-25 train-test split (in favour of train).

**NOTE**: Use 42 as the `random_state` so that we have reproducible splits.

+ *Hint*: did you check the api documentation for [sklearn.model_selection]?
+ *Hint*: did you import the necessary function?

[sklearn.model_selection]: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.model_selection

In [6]:
# your code here
train, test = train_test_split(df, random_state=42)

In [7]:
train.shape

(426, 33)

In [8]:
test.shape

(143, 33)

### 1.3 Use tfdv to compute statistics for the training set
Generate descriptive statistics for the training set using tfdv.

+ *Hint*: you already know what to do...[read the docs]! Look for the appropriate `generate_statistics_from...` method.
+ *Hint*: did you import tensorflow data validation as `tfdv`?

[read the docs]: https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv

In [9]:
# your code here
train_stats = tfdv.generate_statistics_from_dataframe(train)

### 1.4 Visualise training stats & make observations
Lets visualise the statistics for our training set & see how it looks like. In particular, make the following observations:

1. Look at the distribution of the features
1. Look at the range of values for numerical features
1. Look at the values for categorical features
1. Do we have any missing values?
1. Explore the UI: change the feature sort order, change the chart type, etc.

+ *Hint*: there is only one method in tfdv that can do this!

In [10]:
# your code here
tfdv.visualize_statistics(train_stats)

***Reflect on the following questions:***

1. Is the visualisation provided by tfdv useful?
1. Can tfdv be used during data exploration & understanding?
1. Do we have any features that do not follow a *normal distribution*? Will this affect the model's performance?

### 1.5 Visualise testing stats & make observations
Lets now also make sure that our test set is *similar* to our training set. Generate the statistics for the test set & visulise it alongside the train set.

+ *Hint*: did you read the api documentation for the method you used to visualise statistics carefully? Can you visualise statistics of two datasets at the same time?

In [11]:
# your code here
test_stats = tfdv.generate_statistics_from_dataframe(test)
tfdv.visualize_statistics(rhs_statistics=train_stats, lhs_statistics=test_stats, rhs_name="TRAIN", lhs_name="TEST")

***Reflect on the following questions:***

1. Are the training & testing splits similar?
1. Can tfdv be used during data exploration & understanding?

## Part 2: Data Validation
In this section we will write tests for our data. TFDV does this by first creating a *schema* for our data which specifies what we expect our data to look like. In SE terms, the schema is the *test oracle* which we can use to check if our tests are passing or failing.

### 2.1 Create a schema
Generate a schema from the training set.

In [12]:
# your code here
schema = tfdv.infer_schema(train_stats)

### 2.2 Inspect the schema
"Pretty print" the schema that was generated.

In [13]:
# your code here
tfdv.display_schema(schema)

                             Type  Presence Valency       Domain
Feature name
'id'                          INT  required                    -
'diagnosis'                STRING  required          'diagnosis'
'radius_mean'               FLOAT  required                    -
'texture_mean'              FLOAT  required                    -
'perimeter_mean'            FLOAT  required                    -
'area_mean'                 FLOAT  required                    -
'smoothness_mean'           FLOAT  required                    -
'compactness_mean'          FLOAT  required                    -
'concavity_mean'            FLOAT  required                    -
'concave points_mean'       FLOAT  required                    -
'symmetry_mean'             FLOAT  required                    -
'fractal_dimension_mean'    FLOAT  required                    -
'radius_se'                 FLOAT  required                    -
'texture_se'                FLOAT  required                    -
'perimeter_se'              FLOAT  required                    -
'area_se'                   FLOAT  required                    -
'smoothness_se'             FLOAT  required                    -
'compactness_se'            FLOAT  required                    -
'concavity_se'              FLOAT  required                    -
'concave points_se'         FLOAT  required                    -
'symmetry_se'               FLOAT  required                    -
'fractal_dimension_se'      FLOAT  required                    -
'radius_worst'              FLOAT  required                    -
'texture_worst'             FLOAT  required                    -
'perimeter_worst'           FLOAT  required                    -
'area_worst'                FLOAT  required                    -
'smoothness_worst'          FLOAT  required                    -
'compactness_worst'         FLOAT  required                    -
'concavity_worst'           FLOAT  required                    -
'concave points_worst'      FLOAT  required                    -
'symmetry_worst'            FLOAT  required                    -
'fractal_dimension_worst'   FLOAT  required                    -
'Unnamed: 32'               FLOAT  optional                    -

               Values
Domain
'diagnosis'  'B', 'M'

***Reflect on the following:***

+ Does the schema make sense?
+ Does it need to be modified?
+ What about this `Unnamed: 32` column?
+ Do we really need the `id` column?

#### 2.2.1 Cleanup the schema
Drop the columns we don't need & recreate the schema.

In [14]:
# your code here
train = train.drop(columns=['id', 'Unnamed: 32'])
train.shape

(426, 31)

### 2.3 Inspect anomalies in test set
Now lets check if our test set meets the expectations that we define in our schema. First, use tfdv to find the *anomalies* (a.k.a bugs) in our test set and then "pretty print" them.

+ *Hint*: I will give you the answer for this one! You need to use the `validate_statistics` method followed by the appropriate `display...` method.

In [18]:
train_stats = tfdv.generate_statistics_from_dataframe(train)

In [20]:
schema = tfdv.infer_schema(train_stats)

In [21]:
# your code here
anomalies = tfdv.validate_statistics(test_stats, schema=schema)

In [22]:
tfdv.display_anomalies(anomalies)

,Anomaly short description,Anomaly long description
Feature name,,
'Unnamed: 32',New column,New column (column in data but not in schema)
'id',New column,New column (column in data but not in schema)

### (OPTIONAL) 2.4 Make the bugs go away!
Can you fix the issue here? We did this for the training set already!

In [23]:
# your code here
test = test.drop(columns=['Unnamed: 32', 'id'])
test.shape

(143, 31)

In [24]:
test_stats = tfdv.generate_statistics_from_dataframe(test)
anomalies = tfdv.validate_statistics(test_stats, schema=schema)
tfdv.display_anomalies(anomalies)